language: android
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
  - "$HOME/android-sdk-dl"
  - "$HOME/android-sdk"
#android:
#  licenses:
#  - android-sdk-preview-license-.+
#  - android-sdk-license-.+
#  - google-gdk-license-.+
#  components:
#  - tools
#  - tools
#  - platform-tools
#  - build-tools-28.0.2
#  - android-28
#  - extra
#  - sys-img-armeabi-v7a-android-26
stages:
- name: build
  if: branch = master
- name: alpha
  if: branch = alpha
- name: beta
  if: branch = beta
- name: internal
  if: branch = internal
jobs:
  include:
  - stage: build
    before_install:
    # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
    # Latest version available here: https://developer.android.com/studio/#command-tools
    - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
    - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk
    # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools' > /dev/null
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;28.0.2' > /dev/null
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-28' > /dev/null
    - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository' > /dev/null
    - sudo apt-get install -y tar
    - openssl aes-256-cbc -K $encrypted_5ce3e3b113ec_key -iv $encrypted_5ce3e3b113ec_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - ls
    - bundle install
    env:
    - ANDROID_HOME=$HOME/android-sdk
    before_script: chmod +x gradlew
    script: fastlane production
  - stage: alpha
    before_install:
    - sudo apt-get install -y tar
    - openssl aes-256-cbc -K $encrypted_5ce3e3b113ec_key -iv $encrypted_5ce3e3b113ec_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - ls
    - bundle install
    before_script: chmod +x gradlew
    script: fastlane alpha
  - stage: beta
    before_install:
    - sudo apt-get install -y tar
    - openssl aes-256-cbc -K $encrypted_5ce3e3b113ec_key -iv $encrypted_5ce3e3b113ec_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - ls
    - bundle install
    env:
    - ANDROID_HOME=$HOME/android-sdk
    before_script: chmod +x gradlew
    script: fastlane beta
  - stage: internal
    before_install:
    - sudo apt-get install -y tar
    - openssl aes-256-cbc -K $encrypted_5ce3e3b113ec_key -iv $encrypted_5ce3e3b113ec_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - ls
    - bundle install
    before_script:
    - chmod +x gradlew
    - chmod +x travis_commit.sh
    script: fastlane internal
    after_script: bash travis_commit.sh travis-branch-commit

